/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CalcAreaController;
import controller.helpers.HelperCalcArea;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.ModelCalcArea;

/**
 *
 * @author Samuel
 */
public class CalcArea extends javax.swing.JFrame {
private final CalcAreaController controller;
    /**
     * Creates new form CalcArea
     */
    public CalcArea() {
        initComponents();
controller = new CalcAreaController(this);

        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jLabelr = new javax.swing.JLabel();
        jLabelh = new javax.swing.JLabel();
        jLabelb = new javax.swing.JLabel();
        jButtonCalcularT = new javax.swing.JButton();
        jButtonCalcularH = new javax.swing.JButton();
        jTextFieldResultado = new javax.swing.JTextField();
        jButtonCalcularR = new javax.swing.JButton();
        jButtonCalcularT2 = new javax.swing.JButton();
        jTextFieldBaseB = new javax.swing.JTextField();
        jTextFieldRaio = new javax.swing.JTextField();
        jTextFieldHaltura = new javax.swing.JTextField();
        jTextFieldBaseb = new javax.swing.JTextField();
        jButtonCalcTriangulo = new javax.swing.JButton();
        jButtonCalcTrapezio = new javax.swing.JButton();
        jButtonCalcCirculo = new javax.swing.JButton();
        jLabelMenuArea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("2020");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 40, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Feito por: Samuel 2°DS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 200, 20));

        jLabelB.setBackground(new java.awt.Color(0, 0, 0));
        jLabelB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelB.setText("Digite a base \"B\" a maior base:");
        getContentPane().add(jLabelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabelr.setBackground(new java.awt.Color(0, 0, 0));
        jLabelr.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelr.setForeground(new java.awt.Color(255, 255, 255));
        jLabelr.setText("Digite a Raio \"r\" :");
        getContentPane().add(jLabelr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabelh.setBackground(new java.awt.Color(0, 0, 0));
        jLabelh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelh.setForeground(new java.awt.Color(255, 255, 255));
        jLabelh.setText("Digite a haltura \"h\" :");
        getContentPane().add(jLabelh, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jLabelb.setBackground(new java.awt.Color(0, 0, 0));
        jLabelb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelb.setForeground(new java.awt.Color(255, 255, 255));
        jLabelb.setText("Digite a base \"b\" ou a menor base:");
        this.jLabelB.setVisible(false);
        this.jLabelb.setVisible(false);
        this.jLabelr.setVisible(false);
        this.jLabelh.setVisible(false);
        getContentPane().add(jLabelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jButtonCalcularT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/calculo.png"))); // NOI18N
        jButtonCalcularT.setText("Calcular");
        this.jButtonCalcularT.setVisible(false);
        this.jButtonCalcularT2.setVisible(false);
        this.jButtonCalcularH.setVisible(false);
        this.jButtonCalcularR.setVisible(false);
        jButtonCalcularT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcularT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 140, -1));

        jButtonCalcularH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/calculo.png"))); // NOI18N
        jButtonCalcularH.setText("Calcular");
        this.jButtonCalcularT.setVisible(false);
        jButtonCalcularH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularHActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcularH, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 140, -1));

        jTextFieldResultado.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldResultado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFieldResultado.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldResultado.setText("Resultado");
        this.jTextFieldResultado.setVisible(false);
        getContentPane().add(jTextFieldResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 110, 50));

        jButtonCalcularR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/calculo.png"))); // NOI18N
        jButtonCalcularR.setText("Calcular");
        this.jButtonCalcularT.setVisible(false);
        jButtonCalcularR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcularR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 140, -1));

        jButtonCalcularT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/calculo.png"))); // NOI18N
        jButtonCalcularT2.setText("Calcular");
        this.jButtonCalcularT.setVisible(false);
        jButtonCalcularT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularT2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcularT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 140, -1));

        jTextFieldBaseB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        this.jTextFieldBaseB.setVisible(false);
        jTextFieldBaseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBaseBActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBaseB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 230, -1));

        jTextFieldRaio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        this.jTextFieldRaio.setVisible(false);
        jTextFieldRaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRaioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldRaio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 220, -1));

        jTextFieldHaltura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        this.jTextFieldHaltura.setVisible(false);
        jTextFieldHaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHalturaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldHaltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 220, -1));

        jTextFieldBaseb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        this.jTextFieldBaseb.setVisible(false);
        jTextFieldBaseb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBasebActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBaseb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 240, -1));

        jButtonCalcTriangulo.setBackground(new java.awt.Color(153, 0, 0));
        jButtonCalcTriangulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCalcTriangulo.setForeground(new java.awt.Color(204, 204, 204));
        jButtonCalcTriangulo.setText("Triangulo");
        jButtonCalcTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcTrianguloActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 50));

        jButtonCalcTrapezio.setBackground(new java.awt.Color(153, 0, 0));
        jButtonCalcTrapezio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCalcTrapezio.setForeground(new java.awt.Color(204, 204, 204));
        jButtonCalcTrapezio.setText("Trapézio");
        jButtonCalcTrapezio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcTrapezioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcTrapezio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 50));

        jButtonCalcCirculo.setBackground(new java.awt.Color(153, 0, 0));
        jButtonCalcCirculo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCalcCirculo.setForeground(new java.awt.Color(204, 204, 204));
        jButtonCalcCirculo.setText("Circulo");
        jButtonCalcCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcCirculoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, 50));

        jLabelMenuArea.setBackground(new java.awt.Color(51, 51, 255));
        jLabelMenuArea.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelMenuArea.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/menuCalc.jpg"))); // NOI18N
        getContentPane().add(jLabelMenuArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcTrianguloActionPerformed
        // TODO add your handling code here:
       this.controller.limpar();
        this.controller.mostrarTriganulo();
       
    }//GEN-LAST:event_jButtonCalcTrianguloActionPerformed

    private void jButtonCalcTrapezioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcTrapezioActionPerformed
        // TODO add your handling code here:
        this.controller.limpar();
        this.controller.mostrarTrapezio();
    }//GEN-LAST:event_jButtonCalcTrapezioActionPerformed

    private void jButtonCalcCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcCirculoActionPerformed
        // TODO add your handling code here:
        this.controller.limpar();
        this.controller.mostrarCirculo();
        
    }//GEN-LAST:event_jButtonCalcCirculoActionPerformed

    private void jTextFieldBaseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBaseBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBaseBActionPerformed

    private void jTextFieldRaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRaioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRaioActionPerformed

    private void jTextFieldHalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHalturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHalturaActionPerformed

    private void jTextFieldBasebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBasebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBasebActionPerformed

    private void jButtonCalcularTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularTActionPerformed
     System.out.println(jTextFieldBaseb.getText());
        this.controller.calcTriganulo();
       
    }//GEN-LAST:event_jButtonCalcularTActionPerformed

    private void jButtonCalcularT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularT2ActionPerformed
        // TODO add your handling code here:
         this.controller.calcTrapezio();
         
    }//GEN-LAST:event_jButtonCalcularT2ActionPerformed

    private void jButtonCalcularRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularRActionPerformed
        // TODO add your handling code here:
        this.controller.calcCirculo();
        
    }//GEN-LAST:event_jButtonCalcularRActionPerformed

    private void jButtonCalcularHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularHActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButtonCalcularHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcArea().setVisible(true);
                
                
                     
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcCirculo;
    private javax.swing.JButton jButtonCalcTrapezio;
    private javax.swing.JButton jButtonCalcTriangulo;
    private javax.swing.JButton jButtonCalcularH;
    private javax.swing.JButton jButtonCalcularR;
    private javax.swing.JButton jButtonCalcularT;
    private javax.swing.JButton jButtonCalcularT2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelMenuArea;
    private javax.swing.JLabel jLabelb;
    private javax.swing.JLabel jLabelh;
    private javax.swing.JLabel jLabelr;
    private javax.swing.JTextField jTextFieldBaseB;
    private javax.swing.JTextField jTextFieldBaseb;
    private javax.swing.JTextField jTextFieldHaltura;
    private javax.swing.JTextField jTextFieldRaio;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonCalcCirculo() {
        return jButtonCalcCirculo;
    }

    public void setjButtonCalcCirculo(JButton jButtonCalcCirculo) {
        this.jButtonCalcCirculo = jButtonCalcCirculo;
    }

    public JButton getjButtonCalcTrapezio() {
        return jButtonCalcTrapezio;
    }

    public void setjButtonCalcTrapezio(JButton jButtonCalcTrapezio) {
        this.jButtonCalcTrapezio = jButtonCalcTrapezio;
    }

    public JButton getjButtonCalcTriangulo() {
        return jButtonCalcTriangulo;
    }

    public void setjButtonCalcTriangulo(JButton jButtonCalcTriangulo) {
        this.jButtonCalcTriangulo = jButtonCalcTriangulo;
    }

    public JButton getjButtonCalcularT() {
        return jButtonCalcularT;
    }

    public void setjButtonCalcularT(JButton jButtonCalcular) {
        this.jButtonCalcularT = jButtonCalcular;
    }

    public JLabel getjLabelB() {
        return jLabelB;
    }

    public void setjLabelB(JLabel jLabelB) {
        this.jLabelB = jLabelB;
    }

    public JLabel getjLabelMenuArea() {
        return jLabelMenuArea;
    }

    public void setjLabelMenuArea(JLabel jLabelMenuArea) {
        this.jLabelMenuArea = jLabelMenuArea;
    }

    public JLabel getjLabelb() {
        return jLabelb;
    }

    public void setjLabelb(JLabel jLabelb) {
        this.jLabelb = jLabelb;
    }

    public JLabel getjLabelh() {
        return jLabelh;
    }

    public void setjLabelh(JLabel jLabelh) {
        this.jLabelh = jLabelh;
    }

    public JLabel getjLabelr() {
        return jLabelr;
    }

    public void setjLabelr(JLabel jLabelr) {
        this.jLabelr = jLabelr;
    }

    public JTextField getjTextFieldBaseB() {
        return jTextFieldBaseB;
    }

    public void setjTextFieldBaseB(JTextField jTextFieldBaseB) {
        this.jTextFieldBaseB = jTextFieldBaseB;
    }

    public JTextField getjTextFieldBaseb() {
        return jTextFieldBaseb;
    }

    public void setjTextFieldBaseb(JTextField jTextFieldBaseb) {
        this.jTextFieldBaseb = jTextFieldBaseb;
    }

    public JTextField getjTextFieldHaltura() {
        return jTextFieldHaltura;
    }

    public void setjTextFieldHaltura(JTextField jTextFieldHaltura) {
        this.jTextFieldHaltura = jTextFieldHaltura;
    }

    public JTextField getjTextFieldRaio() {
        return jTextFieldRaio;
    }

    public void setjTextFieldRaio(JTextField jTextFieldRaio) {
        this.jTextFieldRaio = jTextFieldRaio;
    }

    public JTextField getjTextFieldResultado() {
        return jTextFieldResultado;
    }

    public void setjTextFieldResultado(JTextField jTextFieldResultado) {
        this.jTextFieldResultado = jTextFieldResultado;
    }

    public JButton getjButtonCalcularH() {
        return jButtonCalcularH;
    }

    public void setjButtonCalcularH(JButton jButtonCalcularH) {
        this.jButtonCalcularH = jButtonCalcularH;
    }

    public JButton getjButtonCalcularR() {
        return jButtonCalcularR;
    }

    public void setjButtonCalcularR(JButton jButtonCalcularR) {
        this.jButtonCalcularR = jButtonCalcularR;
    }

    public JButton getjButtonCalcularT2() {
        return jButtonCalcularT2;
    }

    public void setjButtonCalcularT2(JButton jButtonCalcularT2) {
        this.jButtonCalcularT2 = jButtonCalcularT2;
    }

    
    

    

   
    }




